const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const source = process.argv[2];
if (!source) throw new Error('Pass the Diction source checkout path');
const revision = execFileSync('git', ['-C', source, 'rev-parse', 'HEAD'], {encoding:'utf8',windowsHide:true}).trim();
if (revision !== '2a43ad59fd8f7eab0c529e81e4788412c7c68bbd') throw new Error('Unexpected Diction source revision');
const root = path.join(source, 'gateway');
function replace(file, before, after) {
  const target=path.join(root,file), text=fs.readFileSync(target,'utf8');
  if (text.includes(after)) return;
  if (!text.includes(before)) throw new Error(`Patch does not apply to ${file}`);
  fs.writeFileSync(target,text.replace(before,after));
}
// Keep the native gateway reachable only through the private Tailscale proxy.
replace('main.go','http.ListenAndServe(":"+port, mux)','http.ListenAndServe("127.0.0.1:"+port, mux)');
// Pairing credentials are displayed only by the explicit local QR helper.
replace('main.go','pairing.PrintQR(publicURL, token)','_ = token // Pairing QR is generated by the local pairqr helper.');
replace('core/proxy.go','\tcmd.Stderr = io.Discard','\thideChildWindow(cmd)\n\tcmd.Stderr = io.Discard');
replace('core/streaming.go','\t\t\t\t\t\tcmd.Stderr = &ffmpegStderr','\t\t\t\t\t\thideChildWindow(cmd)\n\t\t\t\t\t\tcmd.Stderr = &ffmpegStderr');
fs.writeFileSync(path.join(root,'core','hidechild_windows.go'),`package core
import ("os/exec"; "syscall")
func hideChildWindow(cmd *exec.Cmd) { cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow:true, CreationFlags:0x08000000} }
`);
const helper=path.join(root,'cmd','pairqr');
fs.mkdirSync(helper,{recursive:true});
fs.copyFileSync(path.join(__dirname,'pairqr.go'),path.join(helper,'main.go'));
const out=path.resolve(__dirname,'..','..','.private','diction','bin');
fs.mkdirSync(out,{recursive:true});
for(const [target,args] of [
  ['diction-gateway.exe',['-ldflags=-H=windowsgui','.']],
  ['diction-pairqr.exe',['./cmd/pairqr']]
]) execFileSync('go',['build','-o',path.join(out,target),...args],{cwd:root,windowsHide:true,stdio:'inherit'});
console.log(`Built Diction gateway and pairing helper from ${revision}`);
